services:
  nginx:
    image: nginx:latest
    container_name: nginx-atv01
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - php

  php:
    image: php:8.1-fpm
    container_name: php-atv01
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./config/php/conf.d:/usr/local/etc/php/conf.d
    networks:
      - app-network

  postgres:
    image: postgres:14
    container_name: postgres-atv01
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    - ./src:/var/www/html
    - ./Bases_de_dados_ver00:/dados